name: Verify

on:
  push:
      branches:
        - 'master'
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - closed

jobs:
  stale:
    # if: github.event_name != 'pull_request' || github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'master'

      - name: verify
        run: |
          docker build -t reproducible-violentmonkey .
